# fly.toml app configuration file generated for flashcard-api-little-glitter-501 on 2025-08-19T14:38:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flashcards-tobias'
primary_region = 'atl'

[build]
  # Using your Dockerfile in /backend
  dockerfile = "./Dockerfile"

[deploy]
  release_command = "alembic -c /app/alembic.ini upgrade head"

[env]
  PORT = "8080"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  soft_limit = 20
  hard_limit = 40

[[http_service.checks]]
  grace_period = "10s"
  interval = "10s"
  method = "GET"
  path = "/health"
  timeout = "2s"

[mounts]
  source = "data"
  destination = "/data"
