[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore:.*You probably want to use `session\.exec\(\)`:DeprecationWarning
    ignore:.*should not be used directly in a SQL statement context.*:sqlalchemy.exc.SADeprecationWarning